const carModels = {
    'Acura': ['ILX', 'MDX', 'NSX', 'RDX', 'TLX', 'ZDX'],
    'Alfa Romeo': ['Giulia', 'Stelvio', '4C', 'Spider', 'Giulietta'],
    'Audi': ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'R8', 'TT'],
    'BMW': ['3 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'X7', 'Z4', 'M2', 'M3', 'M4', 'M5'],
    'Buick': ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal', 'Verano'],
    'Cadillac': ['ATS', 'CT4', 'CT5', 'CT6', 'Escalade', 'XT4', 'XT5', 'XT6', 'CTS', 'XTS'],
    'Chevrolet': ['Bolt', 'Camaro', 'Colorado', 'Equinox', 'Malibu', 'Silverado', 'Traverse', 'Impala', 'Sonic'],
    'Chrysler': ['300', 'Pacifica', 'Voyager', '300C'],
    'Dodge': ['Challenger', 'Charger', 'Durango', 'Viper', 'Journey', 'Grand Caravan'],
    'Fiat': ['500', '124 Spider', '500X', '500L'],
    'Ford': ['Bronco', 'F-150', 'Mustang', 'Escape', 'Explorer', 'Edge', 'Fusion', 'Ranger', 'Expedition', 'Flex'],
    'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
    'GMC': ['Canyon', 'Sierra', 'Terrain', 'Acadia', 'Yukon', 'Sierra HD'],
    'Honda': ['Accord', 'Civic', 'CR-V', 'Pilot', 'Odyssey', 'HR-V', 'Fit', 'Ridgeline'],
    'Hyundai': ['Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Kona', 'Palisade', 'Veloster', 'Kona Electric'],
    'Infiniti': ['Q50', 'Q60', 'QX50', 'QX60', 'QX80', 'Q70', 'G37'],
    'Jaguar': ['F-Pace', 'E-Pace', 'I-Pace', 'XF', 'XJ', 'XE'],
    'Jeep': ['Cherokee', 'Grand Cherokee', 'Wrangler', 'Compass', 'Renegade', 'Gladiator'],
    'Kia': ['Soul', 'Sportage', 'Seltos', 'Telluride', 'Forte', 'Optima', 'Niro', 'Cadenza'],
    'Land Rover': ['Discovery', 'Range Rover', 'Defender', 'Evoque', 'Velar'],
    'Lexus': ['ES', 'GS', 'IS', 'NX', 'RX', 'LX', 'UX', 'RC', 'LC'],
    'Lincoln': ['Aviator', 'Corsair', 'Nautilus', 'Navigator', 'MKZ', 'Continental'],
    'Mazda': ['3', '6', 'CX-3', 'CX-5', 'CX-9', 'MX-5 Miata', 'CX-30'],
    'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'GLA', 'GLC', 'GLE', 'GLS', 'CLA', 'SLC'],
    'Mini': ['Cooper', 'Clubman', 'Countryman', 'Convertible'],
    'Mitsubishi': ['Outlander', 'Eclipse Cross', 'Mirage', 'Lancer', 'Outlander Sport', 'Galant'],
    'Nissan': ['Altima', 'Maxima', '370Z', 'Rogue', 'Murano', 'Pathfinder', 'Titan', 'Versa', 'Juke'],
    'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster', 'Cayman'],
    'Ram': ['1500', '2500', '3500', 'Rebel', 'TRX', 'ProMaster City'],
    'Rivian': ['R1T', 'R1S'],
    'Saab': ['9-3', '9-5'],
    'Subaru': ['Outback', 'Forester', 'Impreza', 'Legacy', 'Ascent', 'WRX'],
    'Tesla': ['Model S', 'Model 3', 'Model X', 'Model Y'],
    'Toyota': ['Camry', 'Corolla', 'Highlander', 'Tacoma', 'RAV4', 'Sienna', 'Land Cruiser', '4Runner', 'Sequoia'],
    'Volkswagen': ['Jetta', 'Passat', 'Tiguan', 'Atlas', 'Golf', 'Arteon', 'Beetle'],
    'Volvo': ['S60', 'S90', 'XC40', 'XC60', 'XC90', 'V60', 'V90'],
    'Aston Martin': ['DB11', 'Vantage', 'DBX'],
    'Bentley': ['Continental GT', 'Flying Spur', 'Bentayga'],
    'Bugatti': ['Chiron', 'Veyron'],
    'Ferrari': ['Portofino', 'F8 Tributo', '812 Superfast', 'Roma', '488 GTB'],
    'Lamborghini': ['Huracán', 'Aventador', 'Urus'],
    'McLaren': ['570S', '720S', 'GT', 'Artura', '600LT'],
    'Maserati': ['Ghibli', 'Levante', 'Quattroporte', 'Alfieri'],
    'Rolls-Royce': ['Phantom', 'Cullinan', 'Ghost', 'Dawn'],
    'Pagani': ['Huayra', 'Zonda'],
    'Plymouth': ['Barracuda', 'Road Runner', 'Duster'],
    'Smart': ['Fortwo', 'Forfour'],
    'Spyker': ['C8 Aileron', 'C8 Laviolette'],
    'Suzuki': ['Vitara', 'Grand Vitara', 'SX4', 'Kizashi'],
    'Zastava': ['Yugo', 'Skala']
};

export default carModels;
